steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'sh'
    args:
      [
        '-c',
        'pack build $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA --builder=gcr.io/buildpacks/builder:v1 --network=cloudbuild --path=.  --env=FIREBASE_SERVER_CONFIG --env=PUBLIC_API_KEY --env=PUBLIC_AUTH_DOMAIN --env=PUBLIC_PROJECT_ID --env=PUBLIC_STORAGE_BUCKET --env=PUBLIC_MESSAGE_SENDER_ID --env=PUBLIC_APP_ID --env=AES_KEY'
      ]
    secretEnv:
      [
        'FIREBASE_SERVER_CONFIG',
        'PUBLIC_API_KEY',
        'PUBLIC_AUTH_DOMAIN',
        'PUBLIC_PROJECT_ID',
        'PUBLIC_STORAGE_BUCKET',
        'PUBLIC_MESSAGE_SENDER_ID',
        'PUBLIC_APP_ID',
        'AES_KEY'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'flake'
      - '--platform=managed'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: projects/482632270682/secrets/FIREBASE_SERVER_CONFIG/versions/latest
      env: 'FIREBASE_SERVER_CONFIG'
    - versionName: projects/482632270682/secrets/PUBLIC_API_KEY/versions/latest
      env: 'PUBLIC_API_KEY'
    - versionName: projects/482632270682/secrets/PUBLIC_AUTH_DOMAIN/versions/latest
      env: 'PUBLIC_AUTH_DOMAIN'
    - versionName: projects/482632270682/secrets/PUBLIC_PROJECT_ID/versions/latest
      env: 'PUBLIC_PROJECT_ID'
    - versionName: projects/482632270682/secrets/PUBLIC_STORAGE_BUCKET/versions/latest
      env: 'PUBLIC_STORAGE_BUCKET'
    - versionName: projects/482632270682/secrets/PUBLIC_MESSAGE_SENDER_ID/versions/latest
      env: 'PUBLIC_MESSAGE_SENDER_ID'
    - versionName: projects/482632270682/secrets/PUBLIC_APP_ID/versions/latest
      env: 'PUBLIC_APP_ID'
    - versionName: projects/482632270682/secrets/AES_KEY/versions/latest
      env: 'AES_KEY'
